### ISSUE TITLE
Peer review?

### ISSUE THREAD

**Issue by leekelleher** [BarryFogarty/Merchello.UkFest.Workshop#1]
Hey @BarryFogarty, would you like me to review the Ditto/DitFlo side of things?

**Comment by BarryFogarty** [comment]
Sure!  NB The default **workshop** branch is now set to the starting point of the workshop session, so you are better off forking either **dev** or **demo-site**.  (or both!)

dev is basically the endpoint of the workshop part.  demo-site is a more complete site build that I am planning to demo/chat about, rather than work through as an exercise with the attendees.

Hey, do you think you could you spare some time on Friday to help out at the workshop?  I'm sure you'll have 1001 other things to do but it would be awesome if you could, even just a pop-in.  The session is actually as much about Ditto/DitFlo as it is Merchello and you'd be able to field questions much better than I.  

No worries if not, just thought I'd ask :-) Its on from 1:30 - 3:30.

**Comment by leekelleher** [comment]
@BarryFogarty Cool, I'll give it a review :+1:   I'd noticed the branch changes, so I re-forked the repo, all good.

Sure, I can come in to the workshop... although may I ask for a favour in return... would you do a Merchello talk at next (or future) umBristol? ;-)

**Comment by BarryFogarty** [comment]
Deal :-)

**Comment by leekelleher** [comment]
Woo! :metal:

**Comment by BarryFogarty** [comment]
NB If you fork dev you might be best of checking out this commit https://github.com/BarryFogarty/Merchello.UkFest.Workshop/commit/523410aa759978973f3a5bafedc2cd52b0f46ce5 as I cleared out the DB content on the commit at the tip.  I might look at reversing the last commit in dev actually, it shouldnt be in that branch.

**Comment by leekelleher** [comment]
OK cool, thanks for the heads up :+1:
